unique_ids:
  assets: {}
  forms: {}
  modules:
    AssessmentEditorForm: QODCB3Q5CIWJLRKJSPTPG365E6YLDZZA
    DashboardForm: C4A2UOGDOVIVO7SEJDLRHVEWQWFKQRFG
    ExamsForm: EKU7TEFNR2QK35KHNN3RUFYEU2ZT5XKO
    ImportExportForm: 7SCOGUVTMTIXOLSZFAUQWCXK2FRJDRIF
    LoginForm: QUESOKAILMOTKN5YNQURMX72NT4TI7W7
    Main: TOSAUID2VV6R2VJ6JZLTMOCDNOAIEW5Y
    NoteEditorForm: ER2LRCN5HOVFHQ64VZCHM3NJQMPMJRKT
    NotesForm: QSXG6J2HJ37NHO26LJYRQHK7K7YF75Z4
    OnboardingForm: KTYVOI5UOHMSCAQBXEBY3YXFLOHPJ67C
    ParserPreviewForm: 6U4P4E5BXS2VNGRJCRVFPR4V2DSUUMZE
    SettingsForm: GKE26V2Z5H4POH57B7FWWJX7ITOL44U2
    common: GZH4Z22ICGO4Z5CKVAUNORXOQKMDDW7L
  scripts: {}
  server_modules:
    _auth: QFPFNCGZUFT7XNUWNFMOT4EKATBY5EMX
    _constants: QRNWCNF4C7IUKIW2HRFRZKMXX6CLDNJJ
    _datetime: 64TOWKEA47ET4QPLWS2IIEYNWZP3QJ4J
    assessments: CUN2W7HUY6CHELYQQOHWOHPL3AYUJWVM
    dashboard: 6D6TLPMT4GZ7NP3NZJRZCYEI2G22YZDR
    exams: 52JJD3VUU6HD5WOE7PYWHLKJKA4KCMUT
    nlp: LE54DXOQZSKCA4GK2I2R432TXLFLYMNU
    notes: 7UF4L4I7EIX5KNFQEQXLEX5NXFS45LIR
    reminders: C6YN3HRU2WHZIBFBY4WPRVRDMUVTUEOM
